curl "http://www.carsales.com.au/carcontent/cs/navigation/top-nav-sprite.png" -o ./src/images/cs/top-nav-sprite.png
curl "http://www.carsales.com.au/carcontent/cs/redesign/mastersprite.png" -o ./src/images/cs/mastersprite.png
curl "http://www.carsales.com.au/carcontent/cs/redesign/make-category-sprite.png" -o ./src/images/cs/make-category-sprite.png
curl "http://www.carsales.com.au/carcontent/cs/redesign/motoring-logo.png" -o ./src/images/cs/motoring-logo.png
curl "http://www.carsales.com.au/carcontent/cs/navigation/multi-logo-sprite.png" -o ./src/images/cs/multi-logo-sprite.png
curl "http://www.carsales.com.au/carcontent/cs/navigation/mega-nav-link-bg.png" -o ./src/images/cs/mega-nav-link-bg.png
curl "http://www.carsales.com.au/carcontent/cs/navigation/mega-menu-sprite.png" -o ./src/images/cs/mega-menu-sprite.png
curl "http://www.carsales.com.au/carcontent/cs/navigation/mega-nav-internal-panel-bg.png" -o ./src/images/cs/mega-nav-internal-panel-bg.png
curl "http://www.carsales.com.au/carcontent/cs/navigation/sprite.png" -o ./src/images/cs/sprite.png